# Generated by Django 5.2.6 on 2025-10-04 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Основной заголовок на главной странице', max_length=500, verbose_name='Заголовок')),
                ('description', models.TextField(help_text='Текст описания под заголовком', verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Hero секция',
                'verbose_name_plural': '01. Hero секция',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['order', '-created_at'], 'verbose_name': 'Проект', 'verbose_name_plural': '03. Проекты'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['order', '-created_at'], 'verbose_name': 'Услуга', 'verbose_name_plural': '02. Услуги'},
        ),
    ]
