# Generated by Django 5.2.6 on 2025-10-04 10:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_herosection_alter_project_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='architect',
            options={'ordering': ['order', '-created_at'], 'verbose_name': 'Архитектор', 'verbose_name_plural': '06. Архитекторы'},
        ),
        migrations.AlterModelOptions(
            name='galleryimage',
            options={'ordering': ['order', '-created_at'], 'verbose_name': 'Изображение галереи', 'verbose_name_plural': '04. Галерея'},
        ),
        migrations.AlterModelOptions(
            name='pressitem',
            options={'ordering': ['order', '-created_at'], 'verbose_name': 'Элемент пресса', 'verbose_name_plural': '05. Пресса о нас'},
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='css_classes',
            field=models.CharField(blank=True, help_text='Дополнительные CSS классы для позиционирования (необязательно)', max_length=200, verbose_name='CSS классы'),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='От 1 до 10. Каждая позиция имеет свое расположение', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Порядок отображения'),
        ),
    ]
