# Generated by Django 5.2.6 on 2025-10-04 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_alter_architect_options_alter_galleryimage_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Press',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Пресса о нас', max_length=200, verbose_name='Заголовок')),
                ('image', models.ImageField(upload_to='press/', verbose_name='Изображение')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Секция пресса',
                'verbose_name_plural': '05. Пресса (секция)',
            },
        ),
        migrations.AlterModelOptions(
            name='pressitem',
            options={'ordering': ['order', '-created_at'], 'verbose_name': 'Элемент пресса', 'verbose_name_plural': '06. Пресса (элементы)'},
        ),
    ]
