# Generated by Django 5.2.6 on 2025-10-04 15:37

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_press_alter_pressitem_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='architect',
            options={'ordering': ['order', '-created_at'], 'verbose_name': 'Архитектор', 'verbose_name_plural': '04. Архитекторы'},
        ),
        migrations.AlterModelOptions(
            name='galleryimage',
            options={'ordering': ['order', '-created_at'], 'verbose_name': 'Изображение галереи', 'verbose_name_plural': '05. Галерея'},
        ),
        migrations.AlterModelOptions(
            name='press',
            options={'verbose_name': 'Секция пресса', 'verbose_name_plural': '06. Пресса (секция)'},
        ),
        migrations.AlterModelOptions(
            name='pressitem',
            options={'ordering': ['order', '-created_at'], 'verbose_name': 'Элемент пресса', 'verbose_name_plural': '07. Пресса (элементы)'},
        ),
        migrations.AddField(
            model_name='project',
            name='model_3d_file',
            field=models.FileField(blank=True, help_text='Загрузите 3D файл проекта (.glb, .gltf, .obj и т.д.)', null=True, upload_to='projects/3d/', verbose_name='3D модель'),
        ),
        migrations.CreateModel(
            name='ProjectCarousel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='projects/carousel/', verbose_name='Изображение')),
                ('order', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Порядок отображения')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carousel_images', to='website.project', verbose_name='Проект')),
            ],
            options={
                'verbose_name': 'Изображение карусели проекта',
                'verbose_name_plural': '03.1 Карусель проектов',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Описание')),
                ('image', models.ImageField(upload_to='projects/details/', verbose_name='Изображение')),
                ('url', models.URLField(blank=True, help_text='Дополнительная ссылка (необязательно)', max_length=500, verbose_name='Ссылка')),
                ('order', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Порядок отображения')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='website.project', verbose_name='Проект')),
            ],
            options={
                'verbose_name': 'Детали проекта',
                'verbose_name_plural': '03.2 Детали проектов',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
