# Generated by Django 5.2.6 on 2025-10-04 16:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_alter_architect_options_alter_galleryimage_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='model_3d_file',
            field=models.FileField(blank=True, help_text='Загрузите 3D файл в формате GLB, GLTF или OBJ (НЕ архив!)', null=True, upload_to='projects/3d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['glb', 'gltf', 'obj'], message='Поддерживаются только форматы: GLB, GLTF, OBJ')], verbose_name='3D модель'),
        ),
    ]
