# Generated by Django 5.2.6 on 2025-10-04 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_alter_project_model_3d_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='model_3d_file',
            field=models.FileField(blank=True, help_text='Загрузите 3D файл проекта (.glb, .gltf, .obj и т.д.)', null=True, upload_to='projects/3d/', verbose_name='3D модель'),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('comment', models.TextField(verbose_name='Комментарий')),
                ('is_active', models.BooleanField(default=False, verbose_name='Опубликован')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='website.project', verbose_name='Проект')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': '08. Отзывы',
                'ordering': ['-created_at'],
            },
        ),
    ]
