# Generated by Django 5.2.6 on 2025-10-04 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_contactinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactinfo',
            name='map_embed_url',
            field=models.URLField(help_text="Только URL из src='...' (без <iframe> тега)", max_length=500, verbose_name='Ссылка для встраивания карты'),
        ),
    ]
