# Generated by Django 5.1.4 on 2025-10-04 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_alter_contactinfo_map_embed_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactinfo',
            name='map_embed_url',
            field=models.TextField(help_text='Вставьте полный <iframe> код из Yandex Maps', verbose_name='Код встраивания карты'),
        ),
    ]
