# Generated by Django 5.1.4 on 2025-10-05 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_alter_contactinfo_map_embed_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('is_processed', models.BooleanField(default=False, verbose_name='Обработано')),
                ('notes', models.TextField(blank=True, help_text='Заметки администратора', verbose_name='Примечания')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='map_embed_url',
            field=models.TextField(verbose_name='Код встраивания карты'),
        ),
        migrations.AlterField(
            model_name='project',
            name='model_3d_file',
            field=models.FileField(blank=True, null=True, upload_to='projects/3d/', verbose_name='3D модель'),
        ),
    ]
