# Generated by Django 5.1.4 on 2025-10-05 05:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_zayavka_delete_feedback'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='zayavka',
            options={'ordering': ['-created_at'], 'verbose_name': 'Заявка', 'verbose_name_plural': '10. Заявки'},
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=50, unique=True, verbose_name='Номер заказа')),
                ('client_name', models.CharField(max_length=200, verbose_name='Имя клиента')),
                ('client_email', models.EmailField(max_length=254, verbose_name='Email клиента')),
                ('client_phone', models.CharField(max_length=20, verbose_name='Телефон клиента')),
                ('project_image', models.ImageField(upload_to='orders/', verbose_name='Изображение проекта')),
                ('status', models.CharField(choices=[('pending', 'Ожидание'), ('in_progress', 'В работе'), ('completed', 'Завершен'), ('cancelled', 'Отменен')], default='pending', max_length=20, verbose_name='Статус')),
                ('start_date', models.DateField(verbose_name='Дата начала')),
                ('end_date', models.DateField(verbose_name='Дата окончания')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='website.project', verbose_name='Проект')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': '11. Заказы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название этапа')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('start_date', models.DateField(verbose_name='Дата начала')),
                ('end_date', models.DateField(verbose_name='Дата окончания')),
                ('status', models.CharField(choices=[('pending', 'Ожидание'), ('in_progress', 'В работе'), ('completed', 'Завершено')], default='pending', max_length=20, verbose_name='Статус')),
                ('order_num', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='website.order', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'Этап заказа',
                'verbose_name_plural': '12. Этапы заказов',
                'ordering': ['order', 'order_num'],
            },
        ),
    ]
