# Generated by Django 5.1.4 on 2025-10-05 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_remove_order_client_email_remove_order_client_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ordertask',
            options={'ordering': ['order', 'id'], 'verbose_name': 'Этап заказа', 'verbose_name_plural': '12. Этапы заказов'},
        ),
    ]
